// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4mw5R_WGNC-J9zDHcGn0plQWzTU1OLNw',
    appId: '1:503570014628:web:30a3bbc370e5f0950a6131',
    messagingSenderId: '503570014628',
    projectId: 'code-campp-app',
    authDomain: 'code-campp-app.firebaseapp.com',
    storageBucket: 'code-campp-app.appspot.com',
    measurementId: 'G-D2YFFSH512',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe0gkImNHYkVxHcdf5V6wZ2OoUOjJSLXQ',
    appId: '1:503570014628:android:42d2a73e7e1bfc830a6131',
    messagingSenderId: '503570014628',
    projectId: 'code-campp-app',
    storageBucket: 'code-campp-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwWtu6cU0HszeANRq9wIrCi6SB8y4w-sE',
    appId: '1:503570014628:ios:4cf34e0540a1ea390a6131',
    messagingSenderId: '503570014628',
    projectId: 'code-campp-app',
    storageBucket: 'code-campp-app.appspot.com',
    iosClientId:
        '503570014628-5buhstjkmbtqib1uin7e01iadigieqkm.apps.googleusercontent.com',
    iosBundleId: 'com.myapp.codecampapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwWtu6cU0HszeANRq9wIrCi6SB8y4w-sE',
    appId: '1:503570014628:ios:eca8362b368460750a6131',
    messagingSenderId: '503570014628',
    projectId: 'code-campp-app',
    storageBucket: 'code-campp-app.appspot.com',
    iosClientId:
        '503570014628-70mschd0cof2mef9dmf5oap85mu4m9sd.apps.googleusercontent.com',
    iosBundleId: 'com.myapp.codecampapp.RunnerTests',
  );
}
